# Generated by Django 2.0.1 on 2018-01-13 15:38

from django.db import migrations
from django.contrib.auth.models import Group


def add_bloggers_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.create(name='Bloggers')

    Permission = apps.get_model('auth', 'Permission')
    for action in ('add', 'change', 'delete'):
        perm = Permission.objects.get(codename='%s_blogpost' % action)
        group.permissions.add(perm)
    group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180112_1732'),
    ]

    operations = [
        migrations.RunPython(add_bloggers_group),
    ]
