# Generated by Django 2.0.1 on 2018-01-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_data_migration_add_bloggers_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorBio',
            new_name='Bio',
        ),
    ]
